CC = gcc
CFLAGS = -Wall

OBJ = linked_list.o main.o

all: main

main: $(OBJ)
	$(CC) $(CFLAGS) -o main $(OBJ)

main.o: linked_list.h main.c

linked_list.o: linked_list.h linked_list.c

clean:
	rm -f *.o
	rm -f linked_list*.o
	rm -f use_linked_list*.*
